import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class AresProtocolScreen extends StatefulWidget {
  const AresProtocolScreen({super.key});

    @override
      State<AresProtocolScreen> createState() => _AresProtocolScreenState();
      }

      class _AresProtocolScreenState extends State<AresProtocolScreen> {
        final TextEditingController _controller = TextEditingController();
          String _status = 'Awaiting command...';
            bool _isLoading = false;

              Future<void> _sendCommand(String type, String details) async {
                  if (_controller.text.isEmpty) {
                        setState(() {
                                _status = 'Error: Identifier field cannot be empty.';
                                      });
                                            return;
                                                }

                                                    setState(() {
                                                          _isLoading = true;
                                                                _status = 'Transmitting signal...';
                                                                    });

                                                                        final url = Uri.parse('https://alkingnbras.pythonanywhere.com/execute');

                                                                            try {
                                                                                  final response = await http.post(
                                                                                          url,
                                                                                                  headers: {'Content-Type': 'application/json'},
                                                                                                          body: json.encode({
                                                                                                                    'type': type,
                                                                                                                              'details': details,
                                                                                                                                        'userInput': _controller.text,
                                                                                                                                                }),
                                                                                                                                                      );

                                                                                                                                                            if (response.statusCode == 200) {
                                                                                                                                                                    setState(() {
                                                                                                                                                                              _status = 'Success: Signal confirmed. Intervention initiated.';
                                                                                                                                                                                      });
                                                                                                                                                                                            } else {
                                                                                                                                                                                                    setState(() {
                                                                                                                                                                                                              _status = 'Failure: Signal rejected. Check server logs.';
                                                                                                                                                                                                                      });
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                      setState(() {
                                                                                                                                                                                                                                              _status = 'Connection Failure: Check network and server status.';
                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                        } finally {
                                                                                                                                                                                                                                                              setState(() {
                                                                                                                                                                                                                                                                      _isLoading = false;
                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                    @override
                                                                                                                                                                                                                                                                                      Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                          return Scaffold(
                                                                                                                                                                                                                                                                                                appBar: AppBar(
                                                                                                                                                                                                                                                                                                        backgroundColor: const Color(0xFF1A1A1A),
                                                                                                                                                                                                                                                                                                                title: const Text('Ares Protocol', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.redAccent)),
                                                                                                                                                                                                                                                                                                                        actions: const [
                                                                                                                                                                                                                                                                                                                                  Padding(
                                                                                                                                                                                                                                                                                                                                              padding: EdgeInsets.only(right: 20.0),
                                                                                                                                                                                                                                                                                                                                                          child: Text('A/G', style: TextStyle(color: Colors.redAccent, fontSize: 18, fontWeight: FontWeight.bold)),
                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                        body: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                padding: const EdgeInsets.all(16.0),
                                                                                                                                                                                                                                                                                                                                                                                                        child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                  crossAxisAlignment: CrossAxisAlignment.stretch,
                                                                                                                                                                                                                                                                                                                                                                                                                            children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                        TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      controller: _controller,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: const TextStyle(color: Colors.white),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  labelText: 'Target Identifier',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  labelStyle: TextStyle(color: Colors.grey),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  enabledBorder: OutlineInputBorder(borderSide: BorderSide(color: Colors.grey)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  focusedBorder: OutlineInputBorder(borderSide: BorderSide(color: Colors.redAccent)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _buildActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  label: 'Initiate Fracture',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                icon: '🛡️',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onPressed: () => _sendCommand('Fracture', 'Urgent report for impersonation and fraudulent activity.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  _buildActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                label: 'Trigger Anomaly',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              icon: '🔥',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onPressed: () => _sendCommand('Anomaly', 'Severe violation report for harassment and explicit content.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _buildActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              label: 'Engage Nullify',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon: '💀',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPressed: () => _sendCommand('Nullify', 'Critical report for political extremism and hate speech.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _buildActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            label: 'Request Paradox',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          icon: '⏳',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: () => _sendCommand('Paradox', 'My account was incorrectly suspended. Please review immediately.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      isRecovery: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const Spacer(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (_isLoading)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const Center(child: CircularProgressIndicator(color: Colors.redAccent))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'Status: $_status',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style: const TextStyle(color: Colors.white70, fontStyle: FontStyle.italic),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Widget _buildActionButton({required String label, required String icon, required VoidCallback onPressed, bool isRecovery = false}) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                final color = isRecovery ? Colors.blueAccent : Colors.redAccent;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return ElevatedButton.icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          icon: Text(icon, style: const TextStyle(fontSize: 20)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                label: Text(label),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: _isLoading ? null : onPressed,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    foregroundColor: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: color.withOpacity(0.8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: const EdgeInsets.symmetric(vertical: 15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            shape: RoundedRectangleBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: BorderRadius.circular(8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                side: BorderSide(color: color),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }